<a href="https://colab.research.google.com/github/abhinavansh18/trials/blob/main/eda_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [49]:
df=pd.read_csv("Algerian_forest_fires_dataset_UPDATE.csv",header=1)
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [50]:
#need to clean the data and manage the missing values
df[df.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,07,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [51]:
df.loc[:122,"Region"]=0
df.loc[122:,"Region"]=1

In [52]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0.0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0.0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0.0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0.0
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0.0

In [53]:
#type conversion of column
df["Region"]=df["Region"].astype(int)

In [54]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0

In [55]:
df.isnull().sum()

day            0
month          1
year           1
Temperature    1
 RH            1
 Ws            1
Rain           1
FFMC           1
DMC            1
DC             1
ISI            1
BUI            1
FWI            1
Classes        2
Region         0
dtype: int64

In [56]:
#remove null
df=df.dropna().reset_index(drop=True)

In [57]:
df.iloc[[122]]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
122,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,1

In [58]:
df=df.drop(122).reset_index(drop=True)

In [59]:
df.iloc[[122]]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
122,01,06,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire,1

In [60]:
df.columns=df.columns.str.strip()
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [61]:
df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws']]=df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws']].astype(int)

In [62]:
#we have to convert all other columns to float as it belongs to object type
objects=[features for features in df.columns if df[features].dtype=='O']
objects

['Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes']

In [63]:
for i in objects:
  if i!='Classes':
    df[i]=df[i].astype(float)

In [64]:
df.to_csv("Algerian_forest_fires_dataset_clean.csv",index=False)

In [65]:
df.info

<bound method DataFrame.info of      day  month  year  Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  \
0      1      6  2012           29  57  18   0.0  65.7   3.4   7.6  1.3   3.4
1      2      6  2012           29  61  13   1.3  64.4   4.1   7.6  1.0   3.9
2      3      6  2012           26  82  22  13.1  47.1   2.5   7.1  0.3   2.7
3      4      6  2012           25  89  13   2.5  28.6   1.3   6.9  0.0   1.7
4      5      6  2012           27  77  16   0.0  64.8   3.0  14.2  1.2   3.9
..   ...    ...   ...          ...  ..  ..   ...   ...   ...   ...  ...   ...
238   26      9  2012           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9
239   27      9  2012           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2
240   28      9  2012           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4
241   29      9  2012           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1
242   30      9  2012           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8

     FWI       Classes  Region
0    0.5   not fire          0
1    0.4   not fire          0
2    0.1   not fire          0
3    0.0   not fire          0
4    0.5   not fire          0
..   ...           ...     ...
238  6.5       fire          1
239  0.0   not fire          1
240  0.2   not fire          1
241  0.7   not fire          1
242  0.5  not fire           1

[243 rows x 15 columns]>

In [66]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [67]:
df_copy=df.drop(['day','month','year'],axis=1)

In [68]:
df_copy['Classes'].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

In [69]:
df_copy['Classes']=np.where(df_copy['Classes'].str.contains('not fire'),0,1)

In [70]:
df_copy['Classes'].value_counts()

Classes
1    137
0    106
Name: count, dtype: int64